// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://amoilwzxtxoczzakyxyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtb2lsd3p4dHhvY3p6YWt5eHl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMTA1MzUsImV4cCI6MjA2OTg4NjUzNX0.0qfDWNa5CZ1R-TEY_y82-O9mceB3C1Qn5BgxViWTSfg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});